### ISSUE TITLE
Single inline

### ISSUE THREAD

**Issue by LeninZapata** [pmkary/comment-vscode#8]
Hello, the extension is incredible, please add the inline-comment in this way.
![example](https://user-images.githubusercontent.com/42600954/51091900-1e591f80-175f-11e9-913c-bf70daf59850.jpg)
and only the first character is with capital letter, the others in minuscule

With this could have better explanation of the code without adding much space, please add this feature 🙏

**Comment by pmkary** [comment]
Hi @LeninZapata. Thanks for using Comment ❤️

Comment implements the [Kary Comments](https://kcs.library.kary.us/kary-comments/introduction) as defined within the Kary Coding Standards. Please read following chapters of the standards to understand the design philosophy of comment:

- [Introduction to Kary Comments](https://kcs.library.kary.us/kary-comments/introduction)
- [Sectioning](https://kcs.library.kary.us/kary-comments/sectioning)
- [Comments Reference](https://kcs.library.kary.us/kary-comments/reference)

Since Comment is a part of [Kary's Coding Umbrella](https://kcs.library.kary.us/karys-coding-umbrella), it is only developed to make the standards possible and not vice versa. So for such changes you may have to fork the tool and tailor it to your custom needs.

All the best regards.
Pouya

**Comment by LeninZapata** [comment]
Is it not possible to customize within the setting?
Anyway, thank you very much

**Comment by pmkary** [comment]
Unfortunately there are no settings for Comments. Since it's a tool developed only for a very specific standard it only implements the standards.

Since I have no contributors and these projects are many, I do not have the time to add the requested features. The only possible form of feature request right now is contributing it yourself. If you have the time to go over the code base then I can help you with adding settings and much more. But I can't add any new features right now.
